/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Gui;

import Classes.Quarto;
import File.FilePersistence;
import Gerenciadores.GerenciadorQuarto;
import Serializadores.SerializadorQuarto;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author USUARIO
 */
public class CadastroQuarto extends javax.swing.JDialog {
    private GerenciadorQuarto  gerente;
    /**
     * Creates new form CadastroQuarto
     */
    
    public CadastroQuarto(java.awt.Frame parent, boolean modal) throws FileNotFoundException {
        super(parent, modal);
        initComponents();
        jTextArea1.setEditable(false);
        gerente = buscarGerente();
        
    }
    public GerenciadorQuarto buscarGerente() throws FileNotFoundException{
        FilePersistence file = new FilePersistence();
        String arquivoLidoReservas = file.loadFromFile("Quartos.txt");
        SerializadorQuarto serializador = new SerializadorQuarto();
        List<Quarto> quartos = serializador.fromCSV(arquivoLidoReservas);
        GerenciadorQuarto gerente = new GerenciadorQuarto();
        gerente.setQuartos(quartos);
        return gerente ;
    }
    public Quarto CampoPraObjeto(){
        Quarto novoQuarto = new Quarto();
        novoQuarto.setNumeroQuarto(edtNomeQuarto.getText());
        novoQuarto.setTipo(etdTipoQuarto.getText());
        novoQuarto.setPrecoPorNoite(Float.parseFloat(edtPrecoQuarto.getText()));
        return novoQuarto;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtNomeQuarto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        etdTipoQuarto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edtPrecoQuarto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CadQuarto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Numero");
        jPanel1.add(jLabel1);
        jPanel1.add(edtNomeQuarto);

        jLabel2.setText("Tipo");
        jPanel1.add(jLabel2);
        jPanel1.add(etdTipoQuarto);

        jLabel3.setText("Preço");
        jPanel1.add(jLabel3);
        jPanel1.add(edtPrecoQuarto);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        CadQuarto.setText("Cadastrar");
        CadQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadQuartoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CadQuarto)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(CadQuarto)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadQuartoActionPerformed
        // TODO add your handling code here:
        Quarto novoQuarto = CampoPraObjeto();
        gerente.addQuarto(novoQuarto);
        try {
            atualizarListagem();
        } catch (IOException ex) {
            Logger.getLogger(CadastroQuarto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CadQuartoActionPerformed
    public void atualizarListagem() throws IOException{
        String listagem = "";
        List<Quarto> quartos = gerente.getQuartos();
        for(Quarto quarto : quartos){
            listagem = listagem+quarto.toString() +"\n";
        }
        jTextArea1.setText(listagem);
        System.out.println(quartos);
        atualizarQuartosNoArquivo(quartos);
        
    }
    public void atualizarQuartosNoArquivo(List<Quarto> listaAtualizada) throws IOException{
        SerializadorQuarto serializador = new SerializadorQuarto();
        String  listaAtualizadaCSV = serializador.toCSV(listaAtualizada);
        FilePersistence atualizarQuartos = new FilePersistence();
        atualizarQuartos.saveToFile(listaAtualizadaCSV, "Quartos.txt");
}
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadQuarto;
    private javax.swing.JTextField edtNomeQuarto;
    private javax.swing.JTextField edtPrecoQuarto;
    private javax.swing.JTextField etdTipoQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
