/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Gui;

import Classes.Hospede;
import File.FilePersistence;
import Gerenciadores.GerenciadorHospede;
import Serializadores.SerializadorHospede;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author USUARIO
 */
public class CadHospede extends javax.swing.JDialog {

    /**
     * Creates new form CadHospede
     */
    private GerenciadorHospede gerente;
    public CadHospede(java.awt.Frame parent, boolean modal) throws FileNotFoundException {
        super(parent, modal);
        initComponents();
        exibirHospedes.setEditable(false);
        gerente = buscarGerente();
    }
    public GerenciadorHospede buscarGerente() throws FileNotFoundException{
        FilePersistence file = new FilePersistence();
        String arquivoLidoReservas = file.loadFromFile("Hospedes.txt");
        SerializadorHospede serializador = new SerializadorHospede();
        List<Hospede> hospedes = serializador.fromCSV(arquivoLidoReservas);
        GerenciadorHospede gerente = new GerenciadorHospede();
        gerente.setHospedes(hospedes);
        return gerente ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtNomeHospede = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edtIdentidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edtNumero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        exibirHospedes = new javax.swing.JTextArea();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1);
        jPanel1.add(edtNomeHospede);

        jLabel2.setText("Identidade:");
        jPanel1.add(jLabel2);

        edtIdentidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtIdentidadeActionPerformed(evt);
            }
        });
        jPanel1.add(edtIdentidade);
        jPanel1.add(jLabel3);

        jLabel4.setText("Endereço:");
        jPanel1.add(jLabel4);
        jPanel1.add(edtEndereco);

        jLabel5.setText("Numero");
        jPanel1.add(jLabel5);
        jPanel1.add(edtNumero);

        exibirHospedes.setColumns(20);
        exibirHospedes.setRows(5);
        jScrollPane1.setViewportView(exibirHospedes);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCadastrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtIdentidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtIdentidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtIdentidadeActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        Hospede novoHospede = campoPraObjeto();
        gerente.addHospede(novoHospede);
        try {
            atualizarListagem();
        } catch (IOException ex) {
            Logger.getLogger(CadHospede.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnCadastrarActionPerformed
    private Hospede campoPraObjeto(){
        Hospede novoHospede = new Hospede();
        novoHospede.setContato(edtNumero.getText());
        novoHospede.setDocumentoIdentidade(edtIdentidade.getText());
        novoHospede.setEndereco(edtEndereco.getText());
        novoHospede.setNome(edtNomeHospede.getText());
        return novoHospede;
    }
    private void atualizarListagem() throws IOException{
        String listagem = "";
        List<Hospede> hospedes = gerente.getHospedes();
        for(Hospede hospede : hospedes){
            listagem = listagem + hospede.toString()+"\n";
        }
        exibirHospedes.setText(listagem);
        atualizarArquivo();
    }
    private void atualizarArquivo() throws IOException{
        SerializadorHospede serializador = new SerializadorHospede();
        String listaCSV = serializador.toCSV(gerente.getHospedes());
        FilePersistence file = new FilePersistence();
        file.saveToFile(listaCSV, "Hospedes.txt");
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtIdentidade;
    private javax.swing.JTextField edtNomeHospede;
    private javax.swing.JTextField edtNumero;
    private javax.swing.JTextArea exibirHospedes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
